### ISSUE TITLE
Bot.py Crashes When Claiming Missions

### ISSUE THREAD

**Issue by NoPurposeInLife** [gexpose/synackAPI#25]
Bot.py Crashes When Claiming Missions

StackTrace:

```
Traceback (most recent call last):
  File "/root/Tools/synackAPI/bot.py", line 71, in <module>
    s1.claimMission(missionJson, dontclaim, assetType)
  File "/root/Tools/synackAPI/synack.py", line 887, in claimMission
    target = self.getCodenameFromSlug(missionJson[key]["listing"]["id"])
KeyError: 'listing'

```

![image](https://user-images.githubusercontent.com/30126475/183336972-7ce13085-3875-4bdc-97ae-7bd2706ea7fe.png)

**Comment by ko2sec** [comment]
I guess mission object is changed and new mission object is as below, maybe it can help to troubleshoot. I removed all sensitive information regarding to the original mission.

`[{"id": "", "title": "", "description": "", "taskTemplateUid": "", "", "campaignName": "", "listingUid": "", "listingCodename": "", "organizationUid": "", "organizationCodename": "", "status": "PUBLISHED", "payout": {"amount": 50, "currency": "USD"}, "credits": 0, "assetTypes": ["Android"], "attackTypes": ["Authentication and Session Management"], "categories": [], "taskType": "MISSION", "batchId": "", "definitionId": "", "taskGroup": "", "scope": "  ", "response": "", "structuredResponse": "", "responseType": "YES_NO", "assignee": "", "reviewer": "", "position": 0, "createdOn": "2022-08-12T00:31:12.836Z", "createdBy": "", "modifiedOn": "2022-08-13T10:53:01.612Z", "modifiedBy": "", "maxCompletionTimeInSecs": 86400, "pausedDurationInSecs": 0, "version": 6, "validResponses": [{"label": "No - customer will see this mission marked as "Passed"", "value": "no"}, {"label": "N/A - target could not be reached/this was otherwise untestable", "value": "n/a"}, {"label": "Yes - customer will see this mission marked as "Failed"", "value": "yes"}], "publish
edOn": "2022-08-12T00:31:12.836Z", "reviewedOn": "2022-08-13T00:36:47Z", "deactivatedOn": None, "canEditResponse": False, "isAssigneeCurrentUser": False, "controlFamily": "", "fismaLow": "", "fismaModerate": "", "fismaHigh": ""}]`

**Comment by h00psn3k** [comment]
This issue has also consistently been cropping up for me. Thank you for posting the new mission object.

**Comment by h00psn3k** [comment]
> This issue has also consistently been cropping up for me. Thank you for posting the new mission object.

Sorry, but could you please double check this object, it has errors in it, I believe. While I can mangle it to be in the correct format, I do not know whether it will necessarily correspond to what the API produces.

**Comment by ko2sec** [comment]
`[{"id": "", "title": "", "description": "", "taskTemplateUid": "", "campaignName": "", "listingUid": "", "listingCodename": "", "organizationUid": "", "organizationCodename": "", "status": "PUBLISHED", "payout": {"amount": 50, "currency": "USD"}, "credits": 0, "assetTypes": ["Android"], "attackTypes": ["Authentication and Session Management"], "categories": [], "taskType": "MISSION", "batchId": "", "definitionId": "", "taskGroup": "", "scope": " ", "response": "", "structuredResponse": "", "responseType": "YES_NO", "assignee": "", "reviewer": "", "position": 0, "createdOn": "2022-08-12T00:31:12.836Z", "createdBy": "", "modifiedOn": "2022-08-13T10:53:01.612Z", "modifiedBy": "", "maxCompletionTimeInSecs": 86400, "pausedDurationInSecs": 0, "version": 6, "validResponses": [{"label": "No - customer will see this mission marked as Passed", "value": "no"}, {"label": "N/A - target could not be reached/this was otherwise untestable", "value": "n/a"}, {"label": "Yes - customer will see this mission marked as Failed", "value": "yes"}], "publish edOn": "2022-08-12T00:31:12.836Z", "reviewedOn": "2022-08-13T00:36:47Z", "deactivatedOn": "", "canEditResponse": false, "isAssigneeCurrentUser": false, "controlFamily": "", "fismaLow": "", "fismaModerate": "", "fismaHigh": ""}]`

It should work, can you try again?

**Comment by h00psn3k** [comment]
It does work, thank you! 

One last thing - do you have a sample of what the mission object used to look like?

**Comment by ko2sec** [comment]
Yes, give a nudge on Slack please.

**Comment by rudSarkar** [comment]
> It does work, thank you!
> 
> One last thing - do you have a sample of what the mission object used to look like?

are you going to add PR?

**Comment by h00psn3k** [comment]
No idea what PR means, sorry

**Comment by rudSarkar** [comment]
Pull Request in this repository

**Comment by h00psn3k** [comment]
Oh! Apologies - I so rarely use GitHub that I did not make the connection. 

If I can get it working, then yes. The problem is that I barely ever get missions as is, so it will take a considerable amount of time for me to positively confirm whether my amendments work.

**Comment by rudSarkar** [comment]
Don't worry, It will be awesome if it gets fixed. I didn't use this for a long time and many things changed in API and rules as well.

**Comment by gexpose** [comment]
There are significant changes to the returned json objects between api v1 and v2. I'm still debating to remove the "bot" functionality from this library altogether.
