### ISSUE TITLE
Error on pop-up for extend session!.

### ISSUE THREAD

**Issue by KathanP19** [gexpose/synackAPI#9]
I kept `bot.py` running in the night and saw this error trace in morning, there was a pop-up on synack platform where we could extend the session by clicking extend button.

Here is the error trace.
```
Connected to platform.
Traceback (most recent call last):
  File "/home/AMBERJACK/2laf781zsm/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/AMBERJACK/2laf781zsm/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/AMBERJACK/2laf781zsm/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/AMBERJACK/2laf781zsm/.local/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/AMBERJACK/2laf781zsm/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/AMBERJACK/2laf781zsm/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/AMBERJACK/2laf781zsm/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/AMBERJACK/2laf781zsm/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/AMBERJACK/2laf781zsm/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='platform.synack.com', port=443): Max retries exceeded with url: /api/tasks/v1/tasks?status=PUBLISHED (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 54, in <module>
    missionJson = s1.pollMissions()
  File "/home/AMBERJACK/2laf781zsm/Desktop/synackAPI/synack.py", line 746, in pollMissions
    response = self.try_requests("GET", self.url_published_missions, 10)
  File "/home/AMBERJACK/2laf781zsm/Desktop/synackAPI/synack.py", line 200, in try_requests
    raise last_err
  File "/home/AMBERJACK/2laf781zsm/Desktop/synackAPI/synack.py", line 168, in try_requests
    response =self.session.get(URL, headers=self.webheaders, verify=False)
  File "/home/AMBERJACK/2laf781zsm/.local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/AMBERJACK/2laf781zsm/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/AMBERJACK/2laf781zsm/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/AMBERJACK/2laf781zsm/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='platform.synack.com', port=443): Max retries exceeded with url: /api/tasks/v1/tasks?status=PUBLISHED (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

```

**Comment by KathanP19** [comment]
![Capture](https://user-images.githubusercontent.com/33719912/141602852-87217663-4118-4e7c-801c-8bfa3a659370.JPG)

**Comment by IfrahIman** [comment]
I'm facing this problem as well.

**Comment by dinosn** [comment]
Hi, this can be caused by several things. The session will expire if the target that you are also is ended on engagement.  Additionally this can also happen on offboarding / paused targets and so on.  I'll advise not to use the gecko, set on your synack.conf `gecko = False`, it will not create a window and it will connect using python's request function. 

Additionally one suggestion is to use polling.py that will keep your token alive, and onboard new targets, together with bot.py.  Both of them using a crontab script that will make sure to keep them up in case of a platform interruption.
